version: '3.1'

services:
  postgres:
    image: postgres
    container_name: postgres-init-data
    restart: always
    ports:
      - 5437:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./scripts/data.sql:/docker-entrypoint-initdb.d/data.sql
volumes:
  postgres: